######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 23 15:21:31 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += rgb2bmp.h tv4l2device.h tvideoimgcapture.h
SOURCES += main.cpp rgb2bmp.cpp tv4l2device.cpp tvideoimgcapture.cpp
